[build]
  publish = "public"
- command = "npm run build"
+ command = ""       # ← 空文字なら「ビルド不要」と認識されます

[functions]
  directory = "netlify/functions"

[[redirects]]
  from   = "/r/:slug"
  to     = "/.netlify/functions/logAndRedirect?slug=:slug"
  status = 200
