[build]
  publish = "."       
  command = ""

[functions]
  directory = "netlify/functions"

[[redirects]]
  from   = "/r/:slug"
  to     = "/.netlify/functions/logAndRedirect?slug=:slug"
  status = 302
  